# Generated by Django 2.1.1 on 2018-09-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='123@123.com', max_length=254, unique=True),
        ),
    ]
